# Biblioteka PyTorch
Biblioteka to zbiór kodu napisanego przez innych programistów z którego można skorzystać. Biblioteka PyTorch udostępnia szereg operacji matematycznych oraz struktury danych znacząco ułatwiających pracę z uczeniem maszynowym. Najważniejszą z tych struktur danych jest tzw. tensor. Tensor jest bardzo specyficzną strukturą danych, która działa podobnie do listy i NumPy array. Aby wyjaśnić działanie tensorów oraz nauczyć cię wykonywać na nich operacje, stworzyłem szereg zadań, mających na celu zilustrowanie, jak z nimi pracować.

In [1]:
# Kod, który importuje tę bibliotekę, umożliwiając ci na skorzystanie z niej
import torch

# W czasie importowania biblioteki torch, uzyskujesz dostęp do wszystkich jej funkcji


## Zadanie 1
Utwórz listę l z elementami 1,2,3,4,5 oraz zamień ją w tensor przy użyciu funkcji torch.tensor(lista). Zamień słowo lista z twoją listą. Następnie, wypisz l.

In [13]:
l = torch.tensor([x for x in range(1,6)])
print(l)

tensor([1, 2, 3, 4, 5])


Wyjściem programu powinno być: tensor([1, 2, 3, 4, 5])

## Zadanie 2
Utwórz drugi tensor o nazwie l2, zawierający elementy 1,2,3. Następnie, dodaj wszystkie elementy z l2 do l. Możesz to zrobić korzystając z funkcji torch.cat((tensor1, tensor2)). Zastąp słowa tensor1 i tensor2 nazwami twoich tensorów. Następnie, wypisz l.

In [15]:
l2 = torch.tensor([x for x in range(1,4)])
l = torch.cat((l, l2))
print(l)

tensor([1, 2, 3, 4, 5, 1, 2, 3])


Wyjściem programu powinno być: tensor([1, 2, 3, 4, 5, 1, 2, 3])

## Zadanie 3
Funkcja torch.zeros(długość), zwraca tensor o długości "długość", który zawiera same zera. Analogicznie działa funkcja torch.ones(długość), z tą różnicą, że nowopowstały tensor posiada tylko i wyłącznie jedynki. Utwórz tensor o nazwie ones, zawierający 10 jedynek oraz tensor o nazwie zeros, zawierający 10 zer. Następnie, wypisz ones i zeros.

In [17]:
torch.ones(10)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Wyjściem programu powinno być:<br>
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])<br>
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Dwuwymiarowe tensory
W przypadku Pythonowych list, możliwe jest umieszczenie list w środku list np. tak jak poniżej: <br>
[[1,2,3],[2,3,4],[1]] <br>
Jak można zauważyć, pierwszym elementem powyższej listy jest lista [1,2,3], drugim jest lista [2,3,4] i trzecim jest lista [1]. Tensory również mogą zawierać inne struktury podobnie jak listy. Co więcej, okazuje się, że jeśli chcecie w jakikolwiek sposób wyciągnąć dane potrzebne do trenowania modeli, bardzo często będziecie musieli na takich dwuwymiarowych tensorach operować. Tensory różnią się jednak pod pewnym względem od Pythonowych list. W Pythonie, jeśli lista zawiera inne listy, każda z list, które ona zawiera mogą być różnej długości, jak na powyższym przykładzie, gdzie pierwsza lista ma długość 3, druga długość 3 i trzecia długość 1. W kontekście tensorów, wszystkie wewnętrzne struktury muszą być tej samej długości.

## Zadanie 4
Korzystając z funkcji torch.zeros((długość1, długość2)), utwórz dwuwymiarowy tensor o nazwie zeros i wymiarach 10x10, zawierający same zera. Następnie, analogicznie, utwórz tensor o nazwie ones i wymiarach 10x5, zawierający same jedynki. Wypisz zeros i ones.

In [21]:
l3 =torch.zeros(10, 10)

In [22]:
l4 = torch.ones(10, 5)

Wyjściem programu powinny być dwa tensory: pierwszy o wymiarach 10x10 zawierający same zera, a drugi o wymiarach 10x5 zawierający same jedynki.

# Łączenie dwuwymiarowych tensorów
Funkcja torch.cat((tensor1, tensor2), dim=a) potrafi nie tylko łączyć ze sobą dwa jednowymiarowe tensory, ale również dwuwymiarowe tensory. Parametr dim odnosi się do konkretnego wymiaru, w którym dwa tensory są ze sobą łączone. Jest to może trochę trudny koncept do zrozumienia (mimo wszystko jak to możliwe, że można coś połączyć na kilka sposobów???), ale mam nadzieję, że wszystko rozjaśni się w praniu.

W PyTorch dim=0 oznacza pierwszy wymiar (wiersze), a dim=1 oznacza drugi wymiar (kolumny).

## Zadanie 5
Używając funkcji torch.cat((tensor1, tensor2), dim=...), utwórz nowy tensor o nazwie a, będący połączeniem ones i zeros. Następnie wypisz a oraz wypisz jego wymiary poprzez napisanie print(a.shape). Pamiętaj, aby zamienić ... przy dim na liczbę, którą uznasz za stosowną. Pewna użyteczna w tym przypadku zasada polega na tym, że jeśli masz dwa tensory o wymiarach nieco się różniących, wtedy jako dim wpisujesz po prostu indeks wymiaru, który się różni między wymiarowościami. Np. jeśli masz tensory o wymiarach kolejno: 8x6 oraz 8x7, wtedy dim=1, natomiast jeśli masz tensor o wymiarach: 6x8, 5x8, wtedy dim=0.

In [24]:
torch.cat((l4, l3), dim=1)

tensor([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Wyjściem programu powinien być tensor o wymiarach (10, 15), gdzie pierwsze 5 kolumn zawiera jedynki, a następne 10 kolumn zera.

## Zadanie 6
Funkcja torch.randn((długość1, długość2)) zwraca dwuwymiarowy tensor o wymiarach długość1 x długość2, zawierający losowe wartości z dystrybucji normalnej. Sposób w jaki możesz rozumieć te losowe wartości to, że są one dowolnymi wartościami w zakresie od -nieskończoność do nieskończoność takimi, że prawdopodobieństwo, że konkretna liczba będzie wylosowana jest tym większe, im bliższa jest ona 0. Np. wartość 1 jest bardziej prawdopodobna niż wartość 2, natomiast wartość -2 jest bardziej prawdopodobna niż wartość -3. Utwórz dwa tensory o nazwach array1 i array2, oba o wymiarach 2 x 6, a następnie połącz je ze sobą na dwa możliwe sposoby, tworząc array3 i array4. Następnie, wypisz array3 i array4 oraz ich kształty. Kształty wypiszesz poprzez napisanie print(array3.shape) oraz print(array4.shape). Array3 powinno mieć kształt 4 x 6, natomiast array4 powinno mieć kształt 2 x 12.

In [26]:
array1 = torch.randn((2,6))
array2 = torch.randn((2,6))

In [30]:
array3 = torch.cat((array1, array2), dim=0)
print(array3)
print(array3.shape)

tensor([[ 1.4496, -0.3034,  0.9796,  1.5745,  0.4396,  1.6483],
        [-0.2115,  0.8165, -0.3215,  0.0975, -1.5469, -0.8746],
        [-2.0235,  0.1447, -0.8398, -0.7320, -1.1403,  0.9839],
        [-0.1195, -0.5371, -0.5868, -0.6820,  0.1087, -1.3902]])
torch.Size([4, 6])


In [31]:
array4 = torch.cat((array1, array2), dim=1)
print(array4)
print(array4.shape)

tensor([[ 1.4496, -0.3034,  0.9796,  1.5745,  0.4396,  1.6483, -2.0235,  0.1447,
         -0.8398, -0.7320, -1.1403,  0.9839],
        [-0.2115,  0.8165, -0.3215,  0.0975, -1.5469, -0.8746, -0.1195, -0.5371,
         -0.5868, -0.6820,  0.1087, -1.3902]])
torch.Size([2, 12])


Wyjściem programu powinny być dwa tensory: pierwszy o wymiarach (4, 6), a drugi o wymiarach (2, 12) wraz z ich kształtami.

# Trójwymiarowe tensory
Dwuwymiarowe tensory można interpretować jako lista zawierająca listy. Trójwymiarowe tensory interpretuje się jako lista zawierająca listy, które same zawierają listy.

Jak zobaczysz w poniższych zadaniach, trójwymiarowe tensory działają analogicznie do dwuwymiarowych.

## Zadanie 7
Utwórz trójwymiarowy tensor, zawierający same zera o nazwie three_dim_array i o wymiarach 2x3x4. Następnie go wypisz oraz jego wymiarowość.

In [33]:
three_dim_array = torch.zeros((2,3,4))
print(three_dim_array)
print(three_dim_array.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


Wyjściem programu powinien być trójwymiarowy tensor o wymiarach (2, 3, 4) zawierający same zera.

## Zadanie 8
Utwórz tensor, zawierający same jedynki o nazwie three_dim_array2 i o wymiarach 2x3x4. Następnie, utwórz 3 nowe tensory o nazwach three_dim_concat1, three_dim_concat2 oraz three_dim_concat3, które reprezentują wszystkie możliwe połączenia three_dim_array oraz three_dim_array2. Na koniec, wypisz je oraz ich wymiarowości.

In [34]:
three_dim_array2 = torch.ones((2,3,4))

In [36]:
three_dim_concat1 = torch.cat((three_dim_array, three_dim_array2), dim=0)
print(three_dim_concat1)
print(three_dim_concat1.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([4, 3, 4])


In [37]:
three_dim_concat1 = torch.cat((three_dim_array, three_dim_array2), dim=1)
print(three_dim_concat1)
print(three_dim_concat1.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
torch.Size([2, 6, 4])


In [38]:
three_dim_concat1 = torch.cat((three_dim_array, three_dim_array2), dim=2)
print(three_dim_concat1)
print(three_dim_concat1.shape)

tensor([[[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.],
         [0., 0., 0., 0., 1., 1., 1., 1.]]])
torch.Size([2, 3, 8])


Wyjściem programu powinny być trzy tensory o następujących wymiarach:<br>
(4, 3, 4)<br>
(2, 6, 4)<br>
(2, 3, 8)<br>

Pierwszy powinien mieć 4 warstwy (2 warstwy zerowe i 2 jedynkowe), drugi powinien mieć 6 podtensorów w drugim wymiarze (3 zerowe i 3 jedynkowe), a trzeci powinien mieć 8 elementów w ostatnim wymiarze (4 zerowe i 4 jedynkowe).