# <div align="center">Prosta Klasyfikacja</div>
---

<img width="500" src="https://upload.wikimedia.org/wikipedia/commons/6/69/Grapevinesnail_01.jpg" alt="Ślimak" />

Źródło: Wikipedia

## Wstęp

Czy zastanawiałeś/aś się kiedyś, jak stworzyć inteligentną maszynę? To samo pytanie zadawał sobie **Heron z Aleksandrii**, sławny m.in. ze wzoru Herona na pole trójkąta.

Pomimo bycia pionierem w tworzeniu zaawansowanych urządzeń mechanicznych i hydraulicznych, nie udało mu się nigdy stworzyć czegoś tak „banalnego” jak konstrukcja rozróżniająca **dwa różne gatunki ślimaków**.

Pewnego dnia, 5-letni **Heron** bawił się w swoim ogrodzie. Zauważył wtedy, że ślimaki, które tam mieszkały, w naturalny sposób dzielą się na dwa typy: jedne mają jaśniejsze muszle, a inne ciemniejsze. Zależało mu szczególnie na uporządkowaniu ich w **dwa wiaderka** - w jednym te jaśniejsze, w drugim ciemniejsze. Niestety, ręczne sortowanie było czasochłonne i mylące, dlatego potrzebował inteligentnego sposobu, który automatycznie i bezbłędnie rozróżni te dwa rodzaje.

Twoim zadaniem jest stworzenie systemu, który nauczy się rozpoznawać cechy ślimaków i przyporządkowywać je do właściwego „wiaderka”, pokazując **Heronowi**, że nowoczesne metody uczenia maszynowego potrafią czynić cuda.

---

## Cel zadania

Celem jest stworzenie modelu uczenia maszynowego, który będzie w stanie poprawnie klasyfikować obrazy ślimaków do jednej z dwóch klas:
- Gatunek 0
- Gatunek 1 

Aby to osiągnąć, wykonasz następujące kroki:

1. **Przygotowanie danych**  
   Do swojego rozwiązania skorzystasz z przygotowanego **zbioru treningowego** zawierającego obrazy ślimaków. Aby upewnić się, że twoje rozwiązanie nie „zna na pamięć” odpowiedzi, a rzeczywiście potrafi niewidziane wcześniej ślimaki odróżniać, zostanie ono przetestowane na **zbiorze walidacyjnym**.

2. **Projektowanie rozwiązania**  
   Zmodyfikujesz funkcję **predict**, aby poprawnie rozpoznawała gatunek ślimaków.

3. **Ostateczny test**  
   Wyślesz swoje rozwiązanie na stronę sprawdzarki, aby sprawdzić jego wynik na niewidzianym wcześniej **zbiorze testowym**. Jest to takie drobne sprawdzenie, czy twoja funkcja nie zwraca zwyczajnie odpowiedzi dostępnych w **zbiorze walidacyjnym** i czy rzeczywiście potrafi odróżniać od siebie oba gatunki.

---

## Wymagania formalne

Formalnie, podczas uruchamiania notatnika dostępne będą pliki:
- `snails.pt` - array NumPy o kształcie `(1000, 4)` (z `dtype=torch.float32` oraz zakresem wartości $[0, 1]$) zawierający czterowymiarowe wektory reprezentujące zmierzone cechy ślimaków.
- `labels.pt` - array NumPy o kształcie `(1000,)` (z `dtype=torch.int64`) zawierający jedynie wartości $0$ lub $1$ reprezentujący gatunki ślimaków do odpowiadających cech z `snails.pt`.
- `snails_valid.pt` - analogiczny do `snails.pt` array NumPy z $400$ przykładami ze zbioru walidacyjnego.
- `labels_valid.pt` - analogiczny do `labels.pt` array NumPy z $400$ etykietami do zbioru walidacyjnego.


Notatnik musi wygenerować plik `predict.pkl` zawierający funkcję `predict` przyjmującą jeden argument będący NumPy Array o kształcie `(400, 4)` i zwracającą jeden NumPy Array typu `int` o kształcie `(400,)` w zależności od przewidzianego gatunku ślimaka. Możesz w tym celu dowolnie zmieniać wszystkie komórki w tym notatniku.

---

## Struktura danych

Każdy punkt danych składa się z $4$ wymiarów, które kolejno reprezentują: średnicę muszli (mm), wysokość muszli (mm), masę (g), jasność muszli znormalizowane do przedziału `[0,1]`.


---

## Dostępne biblioteki

Dostępne biblioteki: `cloudpickle`, `tqdm`, `matplotlib`, `scikit-learn`, `torch`, `numpy`, `pandas`

---

## Ocena

Jakość Twojego rozwiązania zostanie oceniona na podstawie **dokładności klasyfikacji** na zbiorze testowym:

- 🔴 Gdy dokładność ≤ **50%** → **0 punktów**
- 🟢 Gdy dokładność ≥ **95%** → **100 punktów**
- 🟡 W przeciwnym przypadku liczba punktów zostanie obliczona proporcjonalnie według wzoru:


$\text{wynik} = \frac{\text{dokładność} - 0.5}{0.95 - 0.5} \times 100$

---

## Zakładka zgłoszeń

Każde zgłoszenie do tego zadania możesz wysłać na jeden z dwóch zbiorów - walidacyjny lub testowy.

**Zbiór walidacyjny** zawiera te same dane co `snails_valid.pt` oraz `labels_valid.pt`, czyli jest tylko sposobem *walidacji*, czy Twoje rozwiązanie działa poprawnie na naszym systemie (ten notatnik i tak wypisze wynik na zbiorze walidacyjnym). Dlatego nie ma żadnych limitów na wysyłanie zgłoszeń na zbiór walidacyjny (poza tymi, które obowiązaują na całej platformie).

Z kolei **zbiór testowy** jest inny. Nie masz dostępu do tych danych - są one wyłącznie na naszych serwerach. Dzięki temu możemy dobrze sprawdzić, czy Twoje rozwiązanie faktycznie generalizuje na nowych danych. To wynik na zbiorze testowym jest faktycznym wynikiem za to zadanie. Na wysyłanie zgłoszeń na zbiór testowy obowiązuje dodatkowy limit pięciu zgłoszeń dziennie (w zależności od zadania, te limity mogą oczywiście być też inne) - dzięki temu masz pewność, że nie przetrenowałeś swojego algorytmu tak, aby działał specyficznie pod zbiór testowy (co byłoby możliwe po wysłaniu wystarczającej liczby zgłoszeń!).

Po wysłaniu, Twoje zgłoszenie pojawi się w zakładce **zgłoszenia** do tego zadania.
Możesz je tam **kliknąć**, aby zobaczyć jego szczegóły, lub je **anulować**.

Dla ułatwienia, możesz **przesłać** swoje zgłoszenie na zbiór testowy lub walidacyjny. Takie zgłoszenie na odpowiadającym zbiorze wyświetli się wtedy na lewo lub prawo od oryginalnego. Automatycznie wyśle ono te same pliki które były wysłane w oryginalnym zgłoszeniu, ale uruchomi je na drugim zbiorze. Dzięki temu możesz wysłać zgłoszenie na zbiór walidacyjny aby sprawdzić jego poprawność, a następnie ponownie przesłać je na zbiór testowy żeby zobaczyć faktyczny wynik i łatwo porównywać wyniki między tymi zbiorami.

W szczegółach zgłoszenia znajdziesz pola `STDOUT uruchomienia notatnika` oraz `STDERR uruchomienia notatnika`. STDOUT oraz STDERR to standardowe strumienie wyjścia programów komputerowych, w tym uruchamianych plików Python. Pokazujemy je osobno, ponieważ często bardzo przydatnym jest rozdzielenie ich dwóch:
- **STDERR** to strumień przede wszystkim strumień błedów oraz logów. Pojawią się tam wszystkie błędy Twojego notatnika, ostrzeżenia różnych bibliotek oraz np. paski postępu `tqdm`.
- na **STDOUT** idą przede wszystkim wszystkie wywołania funkcji `print()`. Dzięki temu nie będą one się mieszać z różnymi mniej istotnymi logami czy `tqdm`.

---

Pokaż Heronowi, że XXI wiek potrafi odróżnić ślimaki lepiej niż najlepsze starożytne automaty!


# Wymagane biblioteki

Poniższa komórka importuje wymagane biblioteki.

In [14]:
import cloudpickle
import numpy as np
from zipfile import ZipFile
import os

In [15]:
# Ta flaga zostanie automatycznie zmieniona na True na środowisku testowym
# Dzięki temu można uniknąć pobierania plików, co byłoby niemożliwe, bo notatnik nie będzie miał dostępu do internetu
# Możesz również pominąć wykonywanie niektórych operacji które nie są konieczne do wygenerowania odpowiedzi
FINAL_EVALUATION_MODE = False


# Wczytywanie danych

W poniższej komórce wczytamy dane **treningowe** oraz **walidacyjne**.

In [16]:
if not FINAL_EVALUATION_MODE:
    if not os.path.exists('train.zip'):
        !curl -o train.zip https://sprawdzai.org/static/files/dataset/83ada15a-58e2-4bbe-bc7e-5eecff55ca10
        with ZipFile('train.zip', 'r') as z:
            z.extractall()

snails = np.load("snails.npy")
labels = np.load("labels.npy")

snails_valid = np.load("snails_valid.npy")
labels_valid = np.load("labels_valid.npy")


# Twoje rozwiązanie

Poniżej znajdziesz funkcję, którą masz zaimplementować wraz z przykładowym rozwiązaniem otrzymującym 50% dokładności.

In [17]:
snails

array([[0.19140139, 0.2624699 , 0.20735306, 0.71521467],
       [0.12077092, 0.27879685, 0.15055099, 0.8318522 ],
       [0.73241824, 0.87065095, 0.67569035, 0.3390521 ],
       ...,
       [0.24095094, 0.00334037, 0.2443067 , 0.65223235],
       [0.6979714 , 0.80849886, 0.72623336, 0.31741494],
       [0.72105485, 0.71469474, 0.83635896, 0.20497519]],
      shape=(1000, 4), dtype=float32)

In [18]:
labels[:20]

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1])

In [19]:
import torch.nn as nn
import torch

In [20]:
print(labels[:20])
print(np.unique(labels))
print(labels.shape)

[0 0 1 1 0 1 1 1 1 0 0 0 1 1 0 0 0 1 0 1]
[0 1]
(1000,)


In [21]:
labels.dtype

dtype('int64')

In [22]:
y = torch.tensor(labels)
y.dtype

torch.int64

In [23]:
y = torch.tensor(labels, dtype=torch.float32)
y.dtype

torch.float32

In [24]:
X = torch.tensor(snails)

y = torch.tensor(labels, dtype=torch.float32)
y = y.unsqueeze(1)

model = nn.Sequential(
    nn.Linear(4, 16),
    nn.ReLU(),
    nn.Linear(16, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)

criterion = nn.BCEWithLogitsLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(3000):
    logits = model(X)
    loss = criterion(logits, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch % 300 == 0:
        print(epoch, loss.item())

0 0.6987106800079346
300 0.12186645716428757
600 0.008940623141825199
900 0.002436933806166053
1200 0.0009938640287145972
1500 0.0005109673365950584
1800 0.00030109824729152024
2100 0.00019365448679309338
2400 0.0001321774470852688
2700 9.413540101377293e-05


In [25]:
def predict(data):
    X_valid = torch.tensor(data, dtype=torch.float32)

    y_valid = torch.tensor(labels_valid, dtype=torch.float32)
    y_valid = y_valid.unsqueeze(1)

    with torch.no_grad():

        logits = model(X_valid)

        probs = torch.sigmoid(logits)

        preds = (probs > 0.5).float()
        preds = preds.numpy().flatten().astype(np.int64)

    return preds

# Kod oceniający
Ten kod ma na celu ocenienie twojego rozwiązania na dostępnym dla ciebie zbiorze walidacyjnym. Aby nie wliczał się on do limitu czasu, uruchomi się on jedynie u ciebie.

In [26]:
def points(predictions, labels):
    #print(predictions[:20].numpy().flatten())
    predictions = predictions.astype(np.int64)
    labels = labels.astype(np.int64)

    # dokładność
    accuracy = np.mean(predictions == labels)

    acc_min = 0.50
    acc_max = 0.95

    if accuracy <= acc_min:
        return 0, accuracy
    elif accuracy >= acc_max:
        return 100, accuracy
    else:
        score = (accuracy - acc_min) / (acc_max - acc_min) * 100
        return int(score), accuracy


if not FINAL_EVALUATION_MODE:
    pred = predict(snails_valid)

    wynik, dokladnosc = points(pred, labels_valid)

    # Zwyczajne wykonania funkcji 'print' zapisywane są w strumieniu STDOUT, jest on widoczny po wysłaniu notatnika
    # Błędy, wywołania 'print' z argumentem file=sys.stderr oraz paski postępu tqdm zapisywane są w strumieniu STDERR, jest on również widoczny po wysłaniu notatnika
    print(f"Twój wynik na zbiorze walidacyjnym: {wynik} pkt")
    print(f"Dokładność: {dokladnosc * 100:.2f}%")
    

Twój wynik na zbiorze walidacyjnym: 100 pkt
Dokładność: 100.00%


# Zapisywanie rozwiązania

Ta komórka zapisze funkcję `predict` do pliku jako `predict.pkl`. Ostateczna ewaluacja będzie wykonywana poprzez uruchomienie wszystkich komórek z notatnika (przez co funkcja przewidująca będzie miała dostęp do wszystkich zmiennych ze wcześniejszych komórek). Na tym uruchomieniu obliczany jest również czas wykonywania rozwiązania. Następnie, dla zbioru testowego, który jest w etapie uruchamiania notatnika ukryty, zostanie wykorzystana zapisana funkcja `predict` do obliczenia metryki dokładności dla danych testowych.

In [27]:
with open("predict.pkl", "wb") as f:
    cloudpickle.dump(predict, f)
